### ISSUE TITLE
Uncaught TypeError: types.isModuleNamespaceObject is not a function

### ISSUE THREAD

**Issue by fxsecltd** [trs/ftp-srv#100]
Uncaught TypeError: types.isModuleNamespaceObject is not a function
    at formatValue (util.js:664:22)
    at Object.inspect (util.js:328:10)
    at Logger.addStream (C:\Users\123\bpnex\node_modules\bunyan\lib\bunyan.js:581:62)
    at new Logger (C:\Users\123\bpnex\node_modules\bunyan\lib\bunyan.js:490:18)
    at Function.createLogger (C:\Users\123\bpnex\node_modules\bunyan\lib\bunyan.js:1618:12)
    at new FtpServer (C:\Users\123\bpnex\node_modules\ftp-srv\src\index.js:17:18)

**Comment by trs** [comment]
`isModuleNamespaceObject` was [added in 10.0.0](https://nodejs.org/api/util.html#util_util_types_ismodulenamespaceobject_value), but looks like this originated from bunyan, which says it [supports down to 0.10](https://github.com/trentm/node-bunyan#current-status).

What version of node are you using? Can you post a code snippet?

**Comment by fxsecltd** [comment]
I using code trom that link https://github.com/trs/ftp-srv/blob/master/test/start.js
If I comment assertion in bunyan.js - everything is fine, but it is not good workaround.
bunyan.js - line 580
        //assert.ok(isWritable(s.stream), "stream" stream is not writable: ' + util.inspect(s.stream));

**Comment by fxsecltd** [comment]
C:\Users\123\bpnex>node --version
v6.11.4

**Comment by trs** [comment]
Any further progress on this?
