### ISSUE TITLE
GET'ing files that start with '-' (hyphen) crashes server

### ISSUE THREAD

**Issue by broofa** [trs/ftp-srv#120]
This happens with both the CLI and servers created via the API.

Launch the CLI:

`> ftp-srv ftp://localhost:9876 --root ~/work/ftpsrv/ --username`

Then try to GET any file that starts with a hyphen -

```
$ ftp anonymous@localhost 9876

ftp> get -foo
remote: -foo
```
**Expected behavior**: If there's a file named `-foo`, it should `150 File status okay; about to open data connection`.  If no such file exists, it should respond with `551 ENOENT: no such file or directory`

**Actual behavior**:  On the server:

```
Unhandled rejection TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.normalize (path.js:1202:5)
    at serverPath (/Users/kieffer/work/ftpsrv/node_modules/ftp-srv/src/fs.js:21:23)
    at FileSystem._resolvePath (/Users/kieffer/work/ftpsrv/node_modules/ftp-srv/src/fs.js:27:7)
    at FileSystem.get (/Users/kieffer/work/ftpsrv/node_modules/ftp-srv/src/fs.js:45:27)
    at FtpConnection.handler (/Users/kieffer/work/ftpsrv/node_modules/ftp-srv/src/commands/registration/size.js:9:36)
    at FtpCommands.handle (/Users/kieffer/work/ftpsrv/node_modules/ftp-srv/src/commands/index.js:65:28)
    at Promise.mapSeries.message (/Users/kieffer/work/ftpsrv/node_modules/ftp-srv/src/connection.js:44:65)
From previous event:
    at FtpConnection._handleData (/Users/kieffer/work/ftpsrv/node_modules/ftp-srv/src/connection.js:44:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
```

**Comment by broofa** [comment]
'Looks like the problem is at https://github.com/trs/ftp-srv/blob/master/src/commands/index.js#L18 , where any arg that starts with `-` or `--` is considered a flag.  Normally that'd be okay, except the RETR (GET) command doesn't have flags.

**Comment by trs** [comment]
Thanks for the patch!

I'd like to find a resource that outlines what flags are available to which command to improve parsing.

Merging here: https://github.com/trs/ftp-srv/pull/122

**Comment by broofa** [comment]
> I'd like to find a resource that outlines what flags are available to which command to improve parsing.

Are flags even a thing in FTP?  I was a little unclear on why that code was even parsing for them.   RFC959 makes no mention of `flag`s or `option`s, fwiw.

**Comment by trs** [comment]
Some clients send flags on various commands. I'll try to find an example.
It may have been a newer RFC that added it, or they might not even be standard.

**Comment by trs** [comment]
Here's when the code to support flags was merged: https://github.com/trs/ftp-srv/pull/32
Spawned by this issue: https://github.com/trs/ftp-srv/issues/31
