### ISSUE TITLE
Cannot destructure property `port` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by broofa** [trs/ftp-srv#137]
Environment:
```
pi@RWK-Pi:~/fanuc_proxy $ node --version
v10.11.0
pi@RWK-Pi:~/fanuc_proxy $ npm ls ftp-srv
@tend/fanuc_proxy@0.0.1 /home/pi/fanuc_proxy
`-- ftp-srv@3.0.5
```
Seeing this in my logs.
```
/home/pi/fanuc_proxy/node_modules/ftp-srv/src/helpers/find-port.js:25
const {port} = portCheckServer.address();
^
TypeError: Cannot destructure property `port` of 'undefined' or 'null'.
at Server.portCheckServer.once (/home/pi/fanuc_proxy/node_modules/ftp-srv/src/helpers/find-port.js:25:38)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at Server.emit (events.js:208:7)
at emitListeningNT (net.js:1387:10)
at _combinedTickCallback (internal/process/next_tick.js:136:11)
at process._tickCallback (internal/process/next_tick.js:181:9)
```

Related to #63?

**Comment by trs** [comment]
Tracking fix: https://github.com/trs/ftp-srv/pull/143

**Comment by voxsoftware** [comment]
Same issue is solved?
