### ISSUE TITLE
"Passive URL not set. Passive connections not available." when trying to run with node

### ISSUE THREAD

**Issue by FWagner13** [trs/ftp-srv#187]
When I try to run the following code:

```
const FtpSrv = require('ftp-srv');
const ftpServer = new FtpSrv({anonymous: true});
 
ftpServer.on('login', (data, resolve, reject) => { console.log('arriba'); resolve(true); });

ftpServer.listen()
.then(() => { console.log('nicely connected on default host & port') });
```

I receive the following error:
```
{"name":"ftp-srv","hostname":"fwagner13-1513-Mxti","pid":7668,"level":40,"msg":"Passive URL not set. Passive connections not available.","time":"2019-12-26T20:35:59.407Z","v":0}
{"name":"ftp-srv","hostname":"fwagner13-1513-Mxti","pid":7668,"level":50,"err":{"message":"listen EACCES 127.0.0.1:21","name":"Error","stack":"Error: listen EACCES 127.0.0.1:21\n    at Object._errnoException (util.js:992:11)\n    at _exceptionWithHostPort (util.js:1014:20)\n    at Server.setupListenHandle [as _listen2] (net.js:1338:19)\n    at listenInCluster (net.js:1396:12)\n    at doListen (net.js:1505:7)\n    at _combinedTickCallback (internal/process/next_tick.js:141:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n    at Function.Module.runMain (module.js:695:11)\n    at startup (bootstrap_node.js:191:16)\n    at bootstrap_node.js:612:3","code":"EACCES"},"msg":"[Event] error","time":"2019-12-26T20:35:59.415Z","v":0}
```
I've seen in the docs that I do not need to set any host or ports, since the default is ftp://127.0.0.1:21. I tried setting it up, but I get the same error.

Is there any problem with the lib?

**Comment by forstermatth** [comment]
Are you running the executable with permissions to bind to port 21? It looks like your second error is a permissions error.

**Comment by FWagner13** [comment]
I changed the options object to `const ftpServer = new FtpSrv({anonymous: true, url: 'ftp://127.0.0.1:1111'});` and now it worked.
