### ISSUE TITLE
Cannot login remotely

### ISSUE THREAD

**Issue by TAINCERcs** [trs/ftp-srv#191]
When trying to Login to the Server from a remote pc I get this Error:
```
{"name":"ftp-srv","hostname":"debian-2gb-fsn1-1","pid":29495,"id":"09548e23-e3d8-44bc-85a2-9f632b9f440c","directive":"LIST","level":50,"err":{"message":"operation timed out","name":"TimeoutError","stack":"TimeoutError: operation timed out\n    at afterTimeout (/home/te/dist/node_modules/bluebird/js/release/timers.js:46:19)\n at Timeout.timeoutTimeout [as _onTimeout] (/home/te/dist/node_modules/bluebird/js/release/timers.js:76:13)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)"},"msg":"operation timed out","time":"2020-01-10T10:00:25.329Z","v":0}
```

But this is only happening, if I connect via a remote pc. when connecting with FileZilla locally it does work. 

I testet this on:

Fresh Debian 10 with node 10.x
Fresh Ubuntu 18 with node 10.x

**Comment by TAINCERcs** [comment]
Fixed it. silly mistake. 

I didn't set the passive URL to the public IP of my server. after that it works now.
